version: '3.8'

services:
  app:
    image: lockelamore2077/nina 
    container_name: nina-frontend
    environment:
      - MODEL_NAME=hf.co/LockeLamora2077/NiNa  # Specify model
      - ABUSE_API_KEY='' # your abuse.ch api key here
    ports:
      - "8000:8000"
    volumes:
      - 'your_pdf_folder_path':/app/pdf  # Mount PDFs directory from your local directory
    networks:
      - ollama-network

volumes:
  ollama_data: {}

networks:
  ollama-network: {}
